name: Publish to Maven Central

on:
  release:
    types: [created]
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      
      - name: List GPG keys (for debugging)
        run: gpg --list-secret-keys --keyid-format LONG
      
      - name: Publish to Maven Central
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_KEY_NAME: ${{ secrets.GPG_KEY_NAME }}
          GPG_TTY: /dev/null
        run: |
          gpg --version
          # Configure Maven to use specific GPG key and loopback pinentry
          echo "Running maven deploy with explicit GPG configuration"
          mvn -B clean deploy -s .mvn/settings.xml \
            -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} \
            -Dgpg.keyname=${{ secrets.GPG_KEY_NAME }} \
            -X 