name: Publish to Maven Central

on:
  workflow_dispatch:  # Manual trigger
  release:
    types: [created]  # Trigger on new release

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      
      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" > private.asc
          gpg --batch --import private.asc
        
      - name: Build and Publish package
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_KEY_NAME: ${{ secrets.GPG_KEY_NAME }}
        run: |
          # Create settings.xml with GPG passphrase config
          mkdir -p ~/.m2
          echo '<settings>
            <servers>
              <server>
                <id>gpg.passphrase</id>
                <passphrase>${env.GPG_PASSPHRASE}</passphrase>
              </server>
            </servers>
          </settings>' > ~/.m2/settings.xml

          # Build and deploy
          mvn -B clean deploy 