name: Publish to Maven Central

on:
  workflow_dispatch:  # Manual trigger
  release:
    types: [created]  # Trigger on new release
  pull_request:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" > private.asc
          gpg --batch --import private.asc
        
      - name: Build and Publish package
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_KEY_NAME: ${{ secrets.GPG_KEY_NAME }}
        run: |
          # Create settings.xml with proper server configurations
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml << EOF
          <settings>
            <servers>
              <server>
                <id>central</id>
                <username>\${env.MAVEN_USERNAME}</username>
                <password>\${env.MAVEN_PASSWORD}</password>
              </server>
              <server>
                <id>gpg.passphrase</id>
                <passphrase>\${env.GPG_PASSPHRASE}</passphrase>
              </server>
            </servers>
          </settings>
          EOF

          # Build and deploy
          mvn -B clean deploy 