name: Publish Package

on:
  push:
    branches: [ main ]
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven'
        server-id: ossrh
        server-username: ${{ secrets.OSSRH_USERNAME }}
        server-password: ${{ secrets.OSSRH_TOKEN }}
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
        settings-path: ${{ github.workspace }}

    - name: Set Version
      id: set_version
      uses: actions/github-script@v4
      if: github.event_name == 'release'
      with:
        script: |
          const noRef = context.ref.replace('refs/tags/', '')
          const noPrefix = noRef.replace('v', '')
          core.setOutput('version', noPrefix)

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Run tests
      run: mvn -B test --file pom.xml
      
    - name: Check code style
      run: mvn -B checkstyle:check --file pom.xml
      
    - name: Generate Javadoc
      run: mvn -B javadoc:javadoc --file pom.xml

    - name: Publish to Maven Central
      run: |
        if [ "${{ github.event_name }}" == "release" ]; then
          mvn --batch-mode versions:set -DnewVersion=${{ steps.set_version.outputs.version }}
        fi
        mvn --batch-mode deploy -P release
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

