name: Publish Package

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Notify Build Start
      uses: slackapi/slack-github-action@v1.24.0
      with:
        channel-id: 'C0893M7DX45'  # Leave empty to use the webhook's default channel
        slack-message: "🚀 Starting build and publish for notificationapi-java-server-sdk"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Run tests
      run: mvn -B test --file pom.xml
      
    - name: Check code style
      run: mvn -B checkstyle:check --file pom.xml
      
    - name: Generate Javadoc
      run: mvn -B javadoc:javadoc --file pom.xml

    - name: Publish to GitHub Packages
      run: mvn --batch-mode deploy
      env:
        GITHUB_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

    - name: Notify Success
      if: success()
      uses: slackapi/slack-github-action@v1.24.0
      with:
        channel-id: 'C0893M7DX45'  # Leave empty to use the webhook's default channel
        slack-message: "✅ Successfully built and published notificationapi-java-server-sdk"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_SUCCESS_WEBHOOK_URL }}

    - name: Notify Failure
      if: failure()
      uses: slackapi/slack-github-action@v1.24.0
      with:
        channel-id: 'C089K7J4F6D'  # Leave empty to use the webhook's default channel
        slack-message: "❌ Failed to build/publish notificationapi-java-server-sdk\nSee: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_FAILED_WEBHOOK_URL }} 