name: Pull Request Pipeline

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '17' ]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: 'maven'
        server-id: ossrh
        server-username: ${{ secrets.OSSRH_USERNAME }}
        server-password: ${{ secrets.OSSRH_TOKEN }}
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
        settings-path: ${{ github.workspace }}
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Run tests
      run: mvn -B test --file pom.xml
      
    - name: Check code style
      run: mvn -B checkstyle:check --file pom.xml
      
    - name: Generate Javadoc
      run: mvn -B javadoc:javadoc --file pom.xml
        
    - name: Verify GPG signing
      run: mvn -B verify -Dgpg.skip=false -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} --file pom.xml
      env:
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
       
    - name: Test SNAPSHOT deployment (dry-run)
      if: matrix.java == '17' # Only test deployment with the latest Java version
      run: mvn -B deploy -DaltDeploymentRepository=ossrh::default::file://local-deployment -DskipTests
      env:
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }} 