name: Pull Request CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Import GPG key
      run: |
        echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 --decode | gpg --batch --import
        gpg --list-secret-keys --keyid-format LONG

    - name: Build and Publish with Maven
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        GPG_KEY_NAME: ${{secrets.GPG_KEY_NAME}}
      run: |
        export MAVEN_USERNAME=${{ secrets.MAVEN_USERNAME}} && export MAVEN_PASSWORD="${{ secrets.MAVEN_PASSWORD}}" && export GPG_PASSPHRASE=${{ secrets.GPG_PASSPHRASE }} && export GPG_KEY_NAME=${{ secrets.GPG_KEY_NAME }} && mvn clean deploy -Dgpg.passphrase=${{secrets.GPG_PASSPHRASE}}
