name: Pull Request CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Import GPG key
      run: |
        # Setup GPG directory
        mkdir -p ~/.gnupg
        chmod 700 ~/.gnupg
        
        # Write key to file
        echo "${{ secrets.GPG_PRIVATE_KEY }}" > ~/private.key
        
        # Import the key
        gpg --batch --import ~/private.key
        
        # Clean up
        rm ~/private.key
        
        # List imported keys and save the key ID
        gpg --list-secret-keys --keyid-format LONG
        # Verify the key is available with the correct ID
        echo "Verifying key availability with ID: ${{ secrets.GPG_KEY_NAME }}"
        gpg --list-secret-keys ${{ secrets.GPG_KEY_NAME }}

    - name: Build and Publish with Maven
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        GPG_KEY_NAME: ${{secrets.GPG_KEY_NAME}}
      run: |
        # Create settings.xml file
        mkdir -p ~/.m2
        cat > ~/.m2/settings.xml << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
            <servers>
                <server>
                    <id>central</id>
                    <username>\${env.MAVEN_USERNAME}</username>
                    <password>\${env.MAVEN_PASSWORD}</password>
                </server>
                <server>
                    <id>gpg.passphrase</id>
                    <passphrase>\${env.GPG_PASSPHRASE}</passphrase>
                </server>
            </servers>
            <profiles>
                <profile>
                    <id>gpg</id>
                    <properties>
                        <gpg.keyname>\${env.GPG_KEY_NAME}</gpg.keyname>
                        <gpg.passphrase>\${env.GPG_PASSPHRASE}</gpg.passphrase>
                        <gpg.executable>gpg</gpg.executable>
                    </properties>
                </profile>
            </profiles>
            <activeProfiles>
                <activeProfile>gpg</activeProfile>
            </activeProfiles>
        </settings>
        EOF
        
        # Debug GPG configuration
        echo "Configured GPG key: $GPG_KEY_NAME"
        gpg --list-keys $GPG_KEY_NAME
        
        # Set environment variables and run Maven with debug for GPG
        export MAVEN_USERNAME=${{ secrets.MAVEN_USERNAME }}
        export MAVEN_PASSWORD="${{ secrets.MAVEN_PASSWORD }}"
        export GPG_PASSPHRASE=${{ secrets.GPG_PASSPHRASE }}
        export GPG_KEY_NAME=${{ secrets.GPG_KEY_NAME }}
        
        mvn clean deploy -Dgpg.keyname=$GPG_KEY_NAME -Dgpg.passphrase=$GPG_PASSPHRASE --settings ~/.m2/settings.xml
